services:
  - type: web
    name: line-gpt-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ChannelSecret
        sync: false
      - key: ChannelAccessToken
        sync: false
